// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IM.Message.proto

package improto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//service id  0x0003
type IMMsgData struct {
	//cmd id:		0x0301
	FromUserId           uint32   `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToSessionId          uint32   `protobuf:"varint,2,opt,name=to_session_id,json=toSessionId,proto3" json:"to_session_id,omitempty"`
	MsgId                uint32   `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	CreateTime           uint32   `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	MsgType              MsgType  `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3,enum=IM.BaseDefine.MsgType" json:"msg_type,omitempty"`
	MsgData              []byte   `protobuf:"bytes,6,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMMsgData) Reset()         { *m = IMMsgData{} }
func (m *IMMsgData) String() string { return proto.CompactTextString(m) }
func (*IMMsgData) ProtoMessage()    {}
func (*IMMsgData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{0}
}

func (m *IMMsgData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMMsgData.Unmarshal(m, b)
}
func (m *IMMsgData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMMsgData.Marshal(b, m, deterministic)
}
func (m *IMMsgData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMMsgData.Merge(m, src)
}
func (m *IMMsgData) XXX_Size() int {
	return xxx_messageInfo_IMMsgData.Size(m)
}
func (m *IMMsgData) XXX_DiscardUnknown() {
	xxx_messageInfo_IMMsgData.DiscardUnknown(m)
}

var xxx_messageInfo_IMMsgData proto.InternalMessageInfo

func (m *IMMsgData) GetFromUserId() uint32 {
	if m != nil {
		return m.FromUserId
	}
	return 0
}

func (m *IMMsgData) GetToSessionId() uint32 {
	if m != nil {
		return m.ToSessionId
	}
	return 0
}

func (m *IMMsgData) GetMsgId() uint32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *IMMsgData) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *IMMsgData) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_MSG_TYPE_NONE
}

func (m *IMMsgData) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *IMMsgData) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMMsgDataAck struct {
	//cmd id:		0x0302
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            uint32      `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgId                uint32      `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,4,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMMsgDataAck) Reset()         { *m = IMMsgDataAck{} }
func (m *IMMsgDataAck) String() string { return proto.CompactTextString(m) }
func (*IMMsgDataAck) ProtoMessage()    {}
func (*IMMsgDataAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{1}
}

func (m *IMMsgDataAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMMsgDataAck.Unmarshal(m, b)
}
func (m *IMMsgDataAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMMsgDataAck.Marshal(b, m, deterministic)
}
func (m *IMMsgDataAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMMsgDataAck.Merge(m, src)
}
func (m *IMMsgDataAck) XXX_Size() int {
	return xxx_messageInfo_IMMsgDataAck.Size(m)
}
func (m *IMMsgDataAck) XXX_DiscardUnknown() {
	xxx_messageInfo_IMMsgDataAck.DiscardUnknown(m)
}

var xxx_messageInfo_IMMsgDataAck proto.InternalMessageInfo

func (m *IMMsgDataAck) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMMsgDataAck) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMMsgDataAck) GetMsgId() uint32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *IMMsgDataAck) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

type IMMsgDataReadAck struct {
	//cmd id:		0x0303
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            uint32      `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgId                uint32      `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,4,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMMsgDataReadAck) Reset()         { *m = IMMsgDataReadAck{} }
func (m *IMMsgDataReadAck) String() string { return proto.CompactTextString(m) }
func (*IMMsgDataReadAck) ProtoMessage()    {}
func (*IMMsgDataReadAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{2}
}

func (m *IMMsgDataReadAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMMsgDataReadAck.Unmarshal(m, b)
}
func (m *IMMsgDataReadAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMMsgDataReadAck.Marshal(b, m, deterministic)
}
func (m *IMMsgDataReadAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMMsgDataReadAck.Merge(m, src)
}
func (m *IMMsgDataReadAck) XXX_Size() int {
	return xxx_messageInfo_IMMsgDataReadAck.Size(m)
}
func (m *IMMsgDataReadAck) XXX_DiscardUnknown() {
	xxx_messageInfo_IMMsgDataReadAck.DiscardUnknown(m)
}

var xxx_messageInfo_IMMsgDataReadAck proto.InternalMessageInfo

func (m *IMMsgDataReadAck) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetMsgId() uint32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *IMMsgDataReadAck) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

type IMMsgDataReadNotify struct {
	//cmd id:		0x0304
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            uint32      `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgId                uint32      `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,4,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMMsgDataReadNotify) Reset()         { *m = IMMsgDataReadNotify{} }
func (m *IMMsgDataReadNotify) String() string { return proto.CompactTextString(m) }
func (*IMMsgDataReadNotify) ProtoMessage()    {}
func (*IMMsgDataReadNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{3}
}

func (m *IMMsgDataReadNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMMsgDataReadNotify.Unmarshal(m, b)
}
func (m *IMMsgDataReadNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMMsgDataReadNotify.Marshal(b, m, deterministic)
}
func (m *IMMsgDataReadNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMMsgDataReadNotify.Merge(m, src)
}
func (m *IMMsgDataReadNotify) XXX_Size() int {
	return xxx_messageInfo_IMMsgDataReadNotify.Size(m)
}
func (m *IMMsgDataReadNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_IMMsgDataReadNotify.DiscardUnknown(m)
}

var xxx_messageInfo_IMMsgDataReadNotify proto.InternalMessageInfo

func (m *IMMsgDataReadNotify) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetMsgId() uint32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *IMMsgDataReadNotify) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

type IMClientTimeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMClientTimeReq) Reset()         { *m = IMClientTimeReq{} }
func (m *IMClientTimeReq) String() string { return proto.CompactTextString(m) }
func (*IMClientTimeReq) ProtoMessage()    {}
func (*IMClientTimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{4}
}

func (m *IMClientTimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMClientTimeReq.Unmarshal(m, b)
}
func (m *IMClientTimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMClientTimeReq.Marshal(b, m, deterministic)
}
func (m *IMClientTimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMClientTimeReq.Merge(m, src)
}
func (m *IMClientTimeReq) XXX_Size() int {
	return xxx_messageInfo_IMClientTimeReq.Size(m)
}
func (m *IMClientTimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMClientTimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMClientTimeReq proto.InternalMessageInfo

type IMClientTimeRsp struct {
	//cmd id:		0x0306
	ServerTime           uint32   `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMClientTimeRsp) Reset()         { *m = IMClientTimeRsp{} }
func (m *IMClientTimeRsp) String() string { return proto.CompactTextString(m) }
func (*IMClientTimeRsp) ProtoMessage()    {}
func (*IMClientTimeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{5}
}

func (m *IMClientTimeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMClientTimeRsp.Unmarshal(m, b)
}
func (m *IMClientTimeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMClientTimeRsp.Marshal(b, m, deterministic)
}
func (m *IMClientTimeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMClientTimeRsp.Merge(m, src)
}
func (m *IMClientTimeRsp) XXX_Size() int {
	return xxx_messageInfo_IMClientTimeRsp.Size(m)
}
func (m *IMClientTimeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMClientTimeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMClientTimeRsp proto.InternalMessageInfo

func (m *IMClientTimeRsp) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type IMUnreadMsgCntReq struct {
	//cmd id:		0x0307
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AttachData           []byte   `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IMUnreadMsgCntReq) Reset()         { *m = IMUnreadMsgCntReq{} }
func (m *IMUnreadMsgCntReq) String() string { return proto.CompactTextString(m) }
func (*IMUnreadMsgCntReq) ProtoMessage()    {}
func (*IMUnreadMsgCntReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{6}
}

func (m *IMUnreadMsgCntReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMUnreadMsgCntReq.Unmarshal(m, b)
}
func (m *IMUnreadMsgCntReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMUnreadMsgCntReq.Marshal(b, m, deterministic)
}
func (m *IMUnreadMsgCntReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMUnreadMsgCntReq.Merge(m, src)
}
func (m *IMUnreadMsgCntReq) XXX_Size() int {
	return xxx_messageInfo_IMUnreadMsgCntReq.Size(m)
}
func (m *IMUnreadMsgCntReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMUnreadMsgCntReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMUnreadMsgCntReq proto.InternalMessageInfo

func (m *IMUnreadMsgCntReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMUnreadMsgCntReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMUnreadMsgCntRsp struct {
	//cmd id:		0x0308
	UserId               uint32        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalCnt             uint32        `protobuf:"varint,2,opt,name=total_cnt,json=totalCnt,proto3" json:"total_cnt,omitempty"`
	UnreadinfoList       []*UnreadInfo `protobuf:"bytes,3,rep,name=unreadinfo_list,json=unreadinfoList,proto3" json:"unreadinfo_list,omitempty"`
	AttachData           []byte        `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IMUnreadMsgCntRsp) Reset()         { *m = IMUnreadMsgCntRsp{} }
func (m *IMUnreadMsgCntRsp) String() string { return proto.CompactTextString(m) }
func (*IMUnreadMsgCntRsp) ProtoMessage()    {}
func (*IMUnreadMsgCntRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{7}
}

func (m *IMUnreadMsgCntRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMUnreadMsgCntRsp.Unmarshal(m, b)
}
func (m *IMUnreadMsgCntRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMUnreadMsgCntRsp.Marshal(b, m, deterministic)
}
func (m *IMUnreadMsgCntRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMUnreadMsgCntRsp.Merge(m, src)
}
func (m *IMUnreadMsgCntRsp) XXX_Size() int {
	return xxx_messageInfo_IMUnreadMsgCntRsp.Size(m)
}
func (m *IMUnreadMsgCntRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMUnreadMsgCntRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMUnreadMsgCntRsp proto.InternalMessageInfo

func (m *IMUnreadMsgCntRsp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMUnreadMsgCntRsp) GetTotalCnt() uint32 {
	if m != nil {
		return m.TotalCnt
	}
	return 0
}

func (m *IMUnreadMsgCntRsp) GetUnreadinfoList() []*UnreadInfo {
	if m != nil {
		return m.UnreadinfoList
	}
	return nil
}

func (m *IMUnreadMsgCntRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgListReq struct {
	//cmd id:		0x0309
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            uint32      `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgIdBegin           uint32      `protobuf:"varint,4,opt,name=msg_id_begin,json=msgIdBegin,proto3" json:"msg_id_begin,omitempty"`
	MsgCnt               uint32      `protobuf:"varint,5,opt,name=msg_cnt,json=msgCnt,proto3" json:"msg_cnt,omitempty"`
	AttachData           []byte      `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMGetMsgListReq) Reset()         { *m = IMGetMsgListReq{} }
func (m *IMGetMsgListReq) String() string { return proto.CompactTextString(m) }
func (*IMGetMsgListReq) ProtoMessage()    {}
func (*IMGetMsgListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{8}
}

func (m *IMGetMsgListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGetMsgListReq.Unmarshal(m, b)
}
func (m *IMGetMsgListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGetMsgListReq.Marshal(b, m, deterministic)
}
func (m *IMGetMsgListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGetMsgListReq.Merge(m, src)
}
func (m *IMGetMsgListReq) XXX_Size() int {
	return xxx_messageInfo_IMGetMsgListReq.Size(m)
}
func (m *IMGetMsgListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGetMsgListReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMGetMsgListReq proto.InternalMessageInfo

func (m *IMGetMsgListReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMGetMsgListReq) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

func (m *IMGetMsgListReq) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMGetMsgListReq) GetMsgIdBegin() uint32 {
	if m != nil {
		return m.MsgIdBegin
	}
	return 0
}

func (m *IMGetMsgListReq) GetMsgCnt() uint32 {
	if m != nil {
		return m.MsgCnt
	}
	return 0
}

func (m *IMGetMsgListReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

//对于群而言，如果消息数目返回的数值小于请求的cnt,则表示群的消息能拉取的到头了，更早的消息没有权限拉取。
//如果msg_cnt 和 msg_id_begin计算得到的最早消息id与实际返回的最早消息id不一致，说明服务器消息有缺失，需要
//客户端做一个缺失标记，避免下次再次拉取。
type IMGetMsgListRsp struct {
	//cmd id:		0x030a
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            uint32      `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgIdBegin           uint32      `protobuf:"varint,4,opt,name=msg_id_begin,json=msgIdBegin,proto3" json:"msg_id_begin,omitempty"`
	MsgList              []*MsgInfo  `protobuf:"bytes,5,rep,name=msg_list,json=msgList,proto3" json:"msg_list,omitempty"`
	AttachData           []byte      `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMGetMsgListRsp) Reset()         { *m = IMGetMsgListRsp{} }
func (m *IMGetMsgListRsp) String() string { return proto.CompactTextString(m) }
func (*IMGetMsgListRsp) ProtoMessage()    {}
func (*IMGetMsgListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{9}
}

func (m *IMGetMsgListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGetMsgListRsp.Unmarshal(m, b)
}
func (m *IMGetMsgListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGetMsgListRsp.Marshal(b, m, deterministic)
}
func (m *IMGetMsgListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGetMsgListRsp.Merge(m, src)
}
func (m *IMGetMsgListRsp) XXX_Size() int {
	return xxx_messageInfo_IMGetMsgListRsp.Size(m)
}
func (m *IMGetMsgListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGetMsgListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMGetMsgListRsp proto.InternalMessageInfo

func (m *IMGetMsgListRsp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

func (m *IMGetMsgListRsp) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMGetMsgListRsp) GetMsgIdBegin() uint32 {
	if m != nil {
		return m.MsgIdBegin
	}
	return 0
}

func (m *IMGetMsgListRsp) GetMsgList() []*MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetMsgListRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLatestMsgIdReq struct {
	//cmd id: 		0x030b
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            uint32      `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AttachData           []byte      `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMGetLatestMsgIdReq) Reset()         { *m = IMGetLatestMsgIdReq{} }
func (m *IMGetLatestMsgIdReq) String() string { return proto.CompactTextString(m) }
func (*IMGetLatestMsgIdReq) ProtoMessage()    {}
func (*IMGetLatestMsgIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{10}
}

func (m *IMGetLatestMsgIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGetLatestMsgIdReq.Unmarshal(m, b)
}
func (m *IMGetLatestMsgIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGetLatestMsgIdReq.Marshal(b, m, deterministic)
}
func (m *IMGetLatestMsgIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGetLatestMsgIdReq.Merge(m, src)
}
func (m *IMGetLatestMsgIdReq) XXX_Size() int {
	return xxx_messageInfo_IMGetLatestMsgIdReq.Size(m)
}
func (m *IMGetLatestMsgIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGetLatestMsgIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMGetLatestMsgIdReq proto.InternalMessageInfo

func (m *IMGetLatestMsgIdReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMGetLatestMsgIdReq) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

func (m *IMGetLatestMsgIdReq) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMGetLatestMsgIdReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetLatestMsgIdRsp struct {
	//cmd id:		0x030c
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            uint32      `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LatestMsgId          uint32      `protobuf:"varint,4,opt,name=latest_msg_id,json=latestMsgId,proto3" json:"latest_msg_id,omitempty"`
	AttachData           []byte      `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMGetLatestMsgIdRsp) Reset()         { *m = IMGetLatestMsgIdRsp{} }
func (m *IMGetLatestMsgIdRsp) String() string { return proto.CompactTextString(m) }
func (*IMGetLatestMsgIdRsp) ProtoMessage()    {}
func (*IMGetLatestMsgIdRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{11}
}

func (m *IMGetLatestMsgIdRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGetLatestMsgIdRsp.Unmarshal(m, b)
}
func (m *IMGetLatestMsgIdRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGetLatestMsgIdRsp.Marshal(b, m, deterministic)
}
func (m *IMGetLatestMsgIdRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGetLatestMsgIdRsp.Merge(m, src)
}
func (m *IMGetLatestMsgIdRsp) XXX_Size() int {
	return xxx_messageInfo_IMGetLatestMsgIdRsp.Size(m)
}
func (m *IMGetLatestMsgIdRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGetLatestMsgIdRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMGetLatestMsgIdRsp proto.InternalMessageInfo

func (m *IMGetLatestMsgIdRsp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

func (m *IMGetLatestMsgIdRsp) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetLatestMsgId() uint32 {
	if m != nil {
		return m.LatestMsgId
	}
	return 0
}

func (m *IMGetLatestMsgIdRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgByIdReq struct {
	//cmd id: 		0x030d
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            uint32      `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgIdList            []uint32    `protobuf:"varint,4,rep,packed,name=msg_id_list,json=msgIdList,proto3" json:"msg_id_list,omitempty"`
	AttachData           []byte      `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMGetMsgByIdReq) Reset()         { *m = IMGetMsgByIdReq{} }
func (m *IMGetMsgByIdReq) String() string { return proto.CompactTextString(m) }
func (*IMGetMsgByIdReq) ProtoMessage()    {}
func (*IMGetMsgByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{12}
}

func (m *IMGetMsgByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGetMsgByIdReq.Unmarshal(m, b)
}
func (m *IMGetMsgByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGetMsgByIdReq.Marshal(b, m, deterministic)
}
func (m *IMGetMsgByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGetMsgByIdReq.Merge(m, src)
}
func (m *IMGetMsgByIdReq) XXX_Size() int {
	return xxx_messageInfo_IMGetMsgByIdReq.Size(m)
}
func (m *IMGetMsgByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGetMsgByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_IMGetMsgByIdReq proto.InternalMessageInfo

func (m *IMGetMsgByIdReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMGetMsgByIdReq) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

func (m *IMGetMsgByIdReq) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMGetMsgByIdReq) GetMsgIdList() []uint32 {
	if m != nil {
		return m.MsgIdList
	}
	return nil
}

func (m *IMGetMsgByIdReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

type IMGetMsgByIdRsp struct {
	//cmd id:		0x030e
	UserId               uint32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionType          SessionType `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=IM.BaseDefine.SessionType" json:"session_type,omitempty"`
	SessionId            uint32      `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MsgList              []*MsgInfo  `protobuf:"bytes,4,rep,name=msg_list,json=msgList,proto3" json:"msg_list,omitempty"`
	AttachData           []byte      `protobuf:"bytes,20,opt,name=attach_data,json=attachData,proto3" json:"attach_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IMGetMsgByIdRsp) Reset()         { *m = IMGetMsgByIdRsp{} }
func (m *IMGetMsgByIdRsp) String() string { return proto.CompactTextString(m) }
func (*IMGetMsgByIdRsp) ProtoMessage()    {}
func (*IMGetMsgByIdRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6279d312984753, []int{13}
}

func (m *IMGetMsgByIdRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IMGetMsgByIdRsp.Unmarshal(m, b)
}
func (m *IMGetMsgByIdRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IMGetMsgByIdRsp.Marshal(b, m, deterministic)
}
func (m *IMGetMsgByIdRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IMGetMsgByIdRsp.Merge(m, src)
}
func (m *IMGetMsgByIdRsp) XXX_Size() int {
	return xxx_messageInfo_IMGetMsgByIdRsp.Size(m)
}
func (m *IMGetMsgByIdRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IMGetMsgByIdRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IMGetMsgByIdRsp proto.InternalMessageInfo

func (m *IMGetMsgByIdRsp) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IMGetMsgByIdRsp) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_SESSION_TYPE_NONE
}

func (m *IMGetMsgByIdRsp) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *IMGetMsgByIdRsp) GetMsgList() []*MsgInfo {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func (m *IMGetMsgByIdRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

func init() {
	proto.RegisterType((*IMMsgData)(nil), "IM.Message.IMMsgData")
	proto.RegisterType((*IMMsgDataAck)(nil), "IM.Message.IMMsgDataAck")
	proto.RegisterType((*IMMsgDataReadAck)(nil), "IM.Message.IMMsgDataReadAck")
	proto.RegisterType((*IMMsgDataReadNotify)(nil), "IM.Message.IMMsgDataReadNotify")
	proto.RegisterType((*IMClientTimeReq)(nil), "IM.Message.IMClientTimeReq")
	proto.RegisterType((*IMClientTimeRsp)(nil), "IM.Message.IMClientTimeRsp")
	proto.RegisterType((*IMUnreadMsgCntReq)(nil), "IM.Message.IMUnreadMsgCntReq")
	proto.RegisterType((*IMUnreadMsgCntRsp)(nil), "IM.Message.IMUnreadMsgCntRsp")
	proto.RegisterType((*IMGetMsgListReq)(nil), "IM.Message.IMGetMsgListReq")
	proto.RegisterType((*IMGetMsgListRsp)(nil), "IM.Message.IMGetMsgListRsp")
	proto.RegisterType((*IMGetLatestMsgIdReq)(nil), "IM.Message.IMGetLatestMsgIdReq")
	proto.RegisterType((*IMGetLatestMsgIdRsp)(nil), "IM.Message.IMGetLatestMsgIdRsp")
	proto.RegisterType((*IMGetMsgByIdReq)(nil), "IM.Message.IMGetMsgByIdReq")
	proto.RegisterType((*IMGetMsgByIdRsp)(nil), "IM.Message.IMGetMsgByIdRsp")
}

func init() { proto.RegisterFile("IM.Message.proto", fileDescriptor_bb6279d312984753) }

var fileDescriptor_bb6279d312984753 = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcb, 0x4f, 0xd4, 0x40,
	0x18, 0x4f, 0xd9, 0x07, 0xf0, 0x75, 0x01, 0x29, 0x2a, 0x0b, 0x46, 0x69, 0x7a, 0xda, 0xd3, 0x26,
	0xe2, 0xd9, 0x83, 0x0b, 0x09, 0x69, 0x42, 0x3d, 0x54, 0x38, 0x37, 0xc3, 0xf6, 0x6b, 0x1d, 0xdd,
	0x76, 0x96, 0xce, 0xb7, 0x26, 0xfb, 0xbf, 0x78, 0x30, 0xf1, 0xac, 0xff, 0x87, 0x47, 0xef, 0x1e,
	0xfd, 0x23, 0x3c, 0x19, 0x33, 0x33, 0xc5, 0x65, 0xcb, 0xa3, 0x98, 0x98, 0x2c, 0xb7, 0xf2, 0x3d,
	0x86, 0xdf, 0x6b, 0x26, 0x0b, 0x0f, 0xfc, 0xa0, 0x1f, 0xa0, 0x94, 0x2c, 0xc5, 0xfe, 0xb8, 0x10,
	0x24, 0x1c, 0x98, 0x55, 0x76, 0xb7, 0xfc, 0xa0, 0x3f, 0x60, 0x12, 0x0f, 0x31, 0xe1, 0x79, 0x39,
	0xe0, 0xfd, 0xb2, 0x60, 0xd5, 0x0f, 0x02, 0x99, 0x1e, 0x32, 0x62, 0x8e, 0x0b, 0x9d, 0xa4, 0x10,
	0x59, 0x34, 0x91, 0x58, 0x44, 0x3c, 0xee, 0x5a, 0xae, 0xd5, 0x5b, 0x0b, 0x41, 0xd5, 0x4e, 0x25,
	0x16, 0x7e, 0xec, 0x78, 0xb0, 0x46, 0x22, 0x92, 0x28, 0x25, 0x17, 0xb9, 0x1a, 0x59, 0xd2, 0x23,
	0x36, 0x89, 0x37, 0xa6, 0xe6, 0xc7, 0xce, 0x23, 0x68, 0x67, 0x32, 0x55, 0xcd, 0x86, 0x6e, 0xb6,
	0x32, 0x99, 0xfa, 0xb1, 0xb3, 0x07, 0xf6, 0xb0, 0x40, 0x46, 0x18, 0x11, 0xcf, 0xb0, 0xdb, 0x34,
	0x67, 0x9b, 0xd2, 0x09, 0xcf, 0xd0, 0x79, 0x0e, 0x2b, 0x6a, 0x8f, 0xa6, 0x63, 0xec, 0xb6, 0x5c,
	0xab, 0xb7, 0xbe, 0xff, 0xb8, 0x3f, 0x8f, 0x39, 0x90, 0xe9, 0xc9, 0x74, 0x8c, 0xe1, 0x72, 0x66,
	0x3e, 0x9c, 0x1d, 0xb3, 0x12, 0x33, 0x62, 0xdd, 0xb6, 0x6b, 0xf5, 0x3a, 0xba, 0xa5, 0xb9, 0xec,
	0x81, 0xcd, 0x88, 0xd8, 0xf0, 0xad, 0xe9, 0x3e, 0xd4, 0x5d, 0x30, 0x25, 0x35, 0xe0, 0x7d, 0xb4,
	0xa0, 0xf3, 0x97, 0xfa, 0xab, 0xe1, 0x7b, 0x67, 0x1b, 0x96, 0xe7, 0x89, 0xb7, 0x27, 0x86, 0xf4,
	0x53, 0x80, 0x2b, 0x8c, 0x57, 0x65, 0x1d, 0xdf, 0x97, 0xd0, 0xb9, 0xd8, 0xd2, 0x94, 0x9a, 0x9a,
	0xd2, 0x6e, 0x85, 0x52, 0x29, 0x9b, 0xa6, 0x65, 0xcb, 0xd9, 0x1f, 0xde, 0x27, 0x4b, 0xf9, 0x59,
	0xc2, 0x0b, 0x91, 0xc5, 0xf7, 0x0f, 0xe2, 0x67, 0x0b, 0xb6, 0xe6, 0x20, 0xbe, 0x16, 0xc4, 0x93,
	0xe9, 0x3d, 0x43, 0xb9, 0x09, 0x1b, 0x7e, 0x70, 0x30, 0xe2, 0x98, 0x93, 0x8a, 0x59, 0x88, 0xe7,
	0xde, 0x7e, 0xa5, 0x24, 0xc7, 0x2a, 0x2e, 0x12, 0x8b, 0x0f, 0x58, 0x98, 0x74, 0x96, 0xc9, 0x37,
	0x25, 0x35, 0xe3, 0x05, 0xb0, 0xe9, 0x07, 0xa7, 0x79, 0x81, 0x2c, 0x0e, 0x64, 0x7a, 0x90, 0x53,
	0x88, 0xe7, 0x37, 0x33, 0xad, 0x4d, 0xdf, 0x57, 0xeb, 0xca, 0x79, 0x72, 0x7c, 0xf3, 0x79, 0x4f,
	0x60, 0x95, 0x04, 0xb1, 0x51, 0x34, 0xcc, 0xa9, 0x14, 0x6e, 0x45, 0x17, 0x0e, 0x72, 0x72, 0x06,
	0xb0, 0x31, 0xd1, 0x07, 0xf1, 0x3c, 0x11, 0xd1, 0x88, 0x4b, 0xea, 0x36, 0xdc, 0x46, 0xcf, 0xde,
	0xdf, 0xa9, 0x68, 0x64, 0xfe, 0x9d, 0x9f, 0x27, 0x22, 0x5c, 0x9f, 0x6d, 0x1c, 0x73, 0x49, 0xf5,
	0x80, 0x7f, 0x5a, 0x4a, 0xb4, 0x23, 0xa4, 0x40, 0xa6, 0x6a, 0xe3, 0x56, 0xfa, 0x55, 0xcb, 0x96,
	0xfe, 0xc9, 0xb2, 0x4a, 0x4e, 0x1a, 0xd5, 0x9c, 0xb8, 0xd0, 0x31, 0x39, 0x89, 0xce, 0x30, 0xe5,
	0xf9, 0xc5, 0x53, 0xa2, 0xd3, 0x32, 0x50, 0x15, 0x05, 0x4c, 0x4d, 0x28, 0xb1, 0x5a, 0x06, 0x58,
	0xa6, 0x35, 0xae, 0xa7, 0xf9, 0xbb, 0x4a, 0xf3, 0x36, 0x57, 0x16, 0x4d, 0xb3, 0x7c, 0x31, 0xb5,
	0xe3, 0x2d, 0xed, 0xf8, 0x35, 0x2f, 0xa6, 0xb6, 0x5b, 0xc9, 0x71, 0x37, 0x9f, 0xbf, 0xe8, 0x4b,
	0x7d, 0x84, 0x74, 0xcc, 0x08, 0xa5, 0x92, 0xc1, 0x8f, 0x17, 0xe8, 0x75, 0x2d, 0xde, 0xef, 0xd7,
	0xe1, 0x5d, 0x9c, 0x69, 0x1e, 0xac, 0x8d, 0x34, 0x90, 0xa8, 0x7c, 0xca, 0x8c, 0x6b, 0xf6, 0x68,
	0x86, 0xae, 0x9e, 0xd3, 0xb7, 0x4b, 0x21, 0x1c, 0x4c, 0x17, 0xaa, 0xff, 0x33, 0xb0, 0xcb, 0x10,
	0xea, 0x94, 0x35, 0xdd, 0x86, 0xea, 0xeb, 0x0c, 0xde, 0x2d, 0x4f, 0x3f, 0xaa, 0x5c, 0x16, 0xe7,
	0xcd, 0xe5, 0xeb, 0xd2, 0xfc, 0x3f, 0xd7, 0x65, 0xb0, 0x03, 0xdb, 0x43, 0x91, 0xf5, 0x33, 0x91,
	0x4e, 0xde, 0x71, 0xec, 0x13, 0x99, 0x1f, 0x56, 0x67, 0x93, 0xe4, 0xac, 0xad, 0xbf, 0x5e, 0xfc,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x13, 0x0e, 0x85, 0x5f, 0x97, 0x09, 0x00, 0x00,
}
